sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 116013.jm
  wechat:
    appid: wx7d6c3e32118c9fb7
    secret: 5027b2d980a86df4d3651eedf46a256e
  shop:
    address: 北京市海淀区上地十街10号
  # Redis基础连接配置
spring:
  redis:
    host: localhost          # Redis服务器地址
    port: 6379               # Redis服务器端口
    password: foobared               # Redis密码(本地默认无密码)
    database: 0              # 默认使用第0个库(共16个库: db0~db15)
    timeout: 5000ms          # 连接超时时间

